# -*- coding: utf-8 -*-
"""CadastroAluno.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1idA68ohPghxTFvzw5HCc0gWXm1qFaPHl
"""

sala = []
while True:
    acao = int(input('''Digite 1 para adicionar um aluno 
    2 para excluir um aluno 
    3 para atualizar o aluno 
    4 para ver a lista de alunos 
    5 para sair do programa '''))
    if acao == 1:
        aluno = input('Informe o nome do aluno: ')
        sala.append(aluno)
    elif acao == 2:
        aluno = input('Informe o nome do aluno que deseja excluir: ')
        if aluno in sala:
            aluno_x = sala.index(aluno)
            sala.pop(aluno_x)
            print(f'{aluno} excluido(a) com sucesso.')
        else:
            print('O aluno não está cadastrado.')
    elif acao == 3:
        aluno = input('Informe o nome do aluno que deseja atualizar: ')
        if aluno in sala:
            aluno_x = sala.index(aluno)
            sala.pop(aluno_x)
            aluno = input('Informe o nome do aluno: ')
            sala.append(aluno)
            print(f'{aluno} foi adicionado com sucesso.')
            sala.sort()
        else:
            print('O aluno não está cadastrado.')
    elif acao == 4:
        print(sala)
    elif acao == 5:
        break
    else:
        print('Opção inválida')